#!/bin/bash

. $HOME/.bash_profile

cd $HOME/MiLoad

if ./isSwitchOn; then
   cd $HOME/MiLoad
   git fetch origin
   git pull  origin main
   
   now=`date +"%Y-%m-%d_%H:%M:%S"`
   
   ./multi >$now.log
fi
