#!/bin/bash

echo Running 1 copies...

#python3 miload.py -i addresses -s 40 -t 6 | grep overall &
#python3 miload.py -i addresses -s 40 -t 6 | grep overall &
#python3 miload.py -i addresses -s 40 -t 6 | grep overall &

#python3 miload.py -i addresses -s 40 -t 6 | grep overall &
#python3 miload.py -i addresses -s 40 -t 6 | grep overall &
#python3 miload.py -i addresses -s 40 -t 6 | grep overall &

#python3 miload.py -i addresses -s 40 -t 6 -d 20  &
#python3 miload.py -i addresses -s 40 -t 6 -d 20  &
python3 miload.py -i addresses -s 40 -t 6 -d 40 

